troiswa_public_homepage:
    path:     /
    defaults: { _controller: TroiswaPublicBundle:Main:index }

troiswa_public_competences:
    path:     /competences
    defaults: { _controller: TroiswaPublicBundle:Main:competences }

troiswa_public_films:
    path:     /films
    defaults: { _controller: TroiswaPublicBundle:Film:films }

troiswa_public_film:
    path:     /films/{id}
    defaults: { _controller: TroiswaPublicBundle:Film:film }
    requirements:
        id: \d+

troiswa_public_acteurs:
    path:     /acteurs
    defaults: { _controller: TroiswaPublicBundle:Acteur:acteurs }

troiswa_public_acteur:
    path:     /acteurs/{id}
    defaults: { _controller: TroiswaPublicBundle:Acteur:acteur }
    requirements:
        id: \d+

troiswa_public__admin_acteur_ajouter:
    path:     /admin/acteur/ajouter
    defaults: { _controller: TroiswaPublicBundle:Acteur:ajouter }