<?php

namespace Troiswa\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function nbFilmByCategorie()
    {
        $req = $this->getEntityManager()->createQuery(
            'SELECT c.titre, count(f.id) as nbFilm
            FROM TroiswaPublicBundle:Film f
            LEFT JOIN f.categorie c
            GROUP BY c.id'
        );

        return $req->getResult();
    }

    public function getNbFilmByCategorie()
    {
        $req = $this ->getEntityManager()->createQuery(
            'SELECT Count(f.id) as nbFilm, c.titre
            FROM TroiswaPublicBundle:Film f
            LEFT JOIN f.categorie c
            GROUP BY c.id ');

        return $req -> getResult();
    }
}
